-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cl_climatology_years
(
    climatology_year integer NOT NULL,
    climatology_year_range character varying(10) NOT NULL,
    climatology_description character varying(100),
    PRIMARY KEY (climatology_year)
);

CREATE TABLE public.cl_fire_projection_summary
(
    station_id integer NOT NULL,
    rcp_id character varying(10) NOT NULL,
    model_id character varying(30) NOT NULL,
    climatology_year integer NOT NULL,
    avg_annual_cffdi numeric,
    dpy_high numeric,
    dpy_very_high numeric,
    dpy_severe numeric,
    dpy_extreme numeric,
    dpy_catastrophic numeric,
    PRIMARY KEY (station_id, rcp_id, model_id, climatology_year)
);

CREATE TABLE public.cl_humidity_09hours
(
    station_id integer NOT NULL,
    rcp_id character varying(10) NOT NULL,
    model_id character varying(30) NOT NULL,
    climatology_year integer NOT NULL,
    annual numeric,
    djf numeric,
    mam numeric,
    jja numeric,
    son numeric,
    ndjfma numeric,
    mjjaso numeric,
    january numeric,
    february numeric,
    march numeric,
    april numeric,
    may numeric,
    june numeric,
    july numeric,
    august numeric,
    september numeric,
    october numeric,
    november numeric,
    december numeric,
    PRIMARY KEY (station_id, rcp_id, model_id, climatology_year)
);

CREATE TABLE public.cl_humidity_15hours
(
    station_id integer NOT NULL,
    rcp_id character varying(10) NOT NULL,
    model_id character varying(30) NOT NULL,
    climatology_year integer NOT NULL,
    annual numeric,
    djf numeric,
    mam numeric,
    jja numeric,
    son numeric,
    ndjfma numeric,
    mjjaso numeric,
    january numeric,
    february numeric,
    march numeric,
    april numeric,
    may numeric,
    june numeric,
    july numeric,
    august numeric,
    september numeric,
    october numeric,
    november numeric,
    december numeric,
    PRIMARY KEY (station_id, rcp_id, model_id, climatology_year)
);

CREATE TABLE public.cl_maximum_temperatures
(
    station_id integer NOT NULL,
    rcp_id character varying(10) NOT NULL,
    model_id character varying(30) NOT NULL,
    climatology_year integer NOT NULL,
    annual numeric,
    djf numeric,
    mam numeric,
    jja numeric,
    son numeric,
    ndjfma numeric,
    mjjaso numeric,
    january numeric,
    february numeric,
    march numeric,
    april numeric,
    may numeric,
    june numeric,
    july numeric,
    august numeric,
    september numeric,
    october numeric,
    november numeric,
    december numeric,
    PRIMARY KEY (station_id, rcp_id, model_id, climatology_year)
);

CREATE TABLE public.cl_mean_temperatures
(
    station_id integer NOT NULL,
    rcp_id character varying(10) NOT NULL,
    model_id character varying(30) NOT NULL,
    climatology_year integer NOT NULL,
    annual numeric,
    djf numeric,
    mam numeric,
    jja numeric,
    son numeric,
    ndjfma numeric,
    mjjaso numeric,
    january numeric,
    february numeric,
    march numeric,
    april numeric,
    may numeric,
    june numeric,
    july numeric,
    august numeric,
    september numeric,
    october numeric,
    november numeric,
    december numeric,
    PRIMARY KEY (station_id, rcp_id, model_id, climatology_year)
);

CREATE TABLE public.cl_minimum_temperatures
(
    station_id integer NOT NULL,
    rcp_id character varying(10) NOT NULL,
    model_id character varying(30) NOT NULL,
    climatology_year integer NOT NULL,
    annual numeric,
    djf numeric,
    mam numeric,
    jja numeric,
    son numeric,
    ndjfma numeric,
    mjjaso numeric,
    january numeric,
    february numeric,
    march numeric,
    april numeric,
    may numeric,
    june numeric,
    july numeric,
    august numeric,
    september numeric,
    october numeric,
    november numeric,
    december numeric,
    PRIMARY KEY (station_id, rcp_id, model_id, climatology_year)
);

CREATE TABLE public.cl_models
(
    model_id character varying(30) NOT NULL,
    model_description character varying(100),
    PRIMARY KEY (model_id)
);

CREATE TABLE public.cl_rcp
(
    rcp_id character varying(10) NOT NULL,
    rcp_description character varying(100),
    PRIMARY KEY (rcp_id)
);

CREATE TABLE public.cl_stations
(
    station_id integer NOT NULL,
    station_name_long character varying(100),
    station_name_short character varying(50),
    lat numeric NOT NULL,
    lon numeric NOT NULL,
    PRIMARY KEY (station_id)
);

CREATE TABLE public.humidity_09hours_raw
(
    "STATION_NAME" character varying(100),
    "STN_ID" integer,
    "LAT" numeric,
    "LON" numeric,
    "ENSEMBLE" character varying(30),
    "RCP" character varying(30),
    "MODEL" character varying(30),
    "CLIMATOLOGY" character varying(30),
    "Annual" numeric,
    "DJF" numeric,
    "MAM" numeric,
    "JJA" numeric,
    "SON" numeric,
    "NDJFMA" numeric,
    "MJJASO" numeric,
    "January" numeric,
    "February" numeric,
    "March" numeric,
    "April" numeric,
    "May" numeric,
    "June" numeric,
    "July" numeric,
    "August" numeric,
    "September" numeric,
    "October" numeric,
    "November" numeric,
    "December" numeric
);

CREATE TABLE public.humidity_15hours_raw
(
    "STATION_NAME" character varying(100),
    "STN_ID" integer,
    "LAT" numeric,
    "LON" numeric,
    "ENSEMBLE" character varying(30),
    "RCP" character varying(30),
    "MODEL" character varying(30),
    "CLIMATOLOGY" character varying(30),
    "Annual" numeric,
    "DJF" numeric,
    "MAM" numeric,
    "JJA" numeric,
    "SON" numeric,
    "NDJFMA" numeric,
    "MJJASO" numeric,
    "January" numeric,
    "February" numeric,
    "March" numeric,
    "April" numeric,
    "May" numeric,
    "June" numeric,
    "July" numeric,
    "August" numeric,
    "September" numeric,
    "October" numeric,
    "November" numeric,
    "December" numeric
);

CREATE TABLE public.maximum_temperatures_raw
(
    "STATION_NAME" character varying(100),
    "STN_ID" integer,
    "LAT" numeric,
    "LON" numeric,
    "ENSEMBLE" character varying(30),
    "RCP" character varying(30),
    "MODEL" character varying(30),
    "CLIMATOLOGY" character varying(30),
    "Annual" numeric,
    "DJF" numeric,
    "MAM" numeric,
    "JJA" numeric,
    "SON" numeric,
    "NDJFMA" numeric,
    "MJJASO" numeric,
    "January" numeric,
    "February" numeric,
    "March" numeric,
    "April" numeric,
    "May" numeric,
    "June" numeric,
    "July" numeric,
    "August" numeric,
    "September" numeric,
    "October" numeric,
    "November" numeric,
    "December" numeric
);

CREATE TABLE public.mean_temperatures_raw
(
    "STATION_NAME" character varying(100),
    "STN_ID" integer,
    "LAT" numeric,
    "LON" numeric,
    "ENSEMBLE" character varying(30),
    "RCP" character varying(30),
    "MODEL" character varying(30),
    "CLIMATOLOGY" character varying(30),
    "Annual" numeric,
    "DJF" numeric,
    "MAM" numeric,
    "JJA" numeric,
    "SON" numeric,
    "NDJFMA" numeric,
    "MJJASO" numeric,
    "January" numeric,
    "February" numeric,
    "March" numeric,
    "April" numeric,
    "May" numeric,
    "June" numeric,
    "July" numeric,
    "August" numeric,
    "September" numeric,
    "October" numeric,
    "November" numeric,
    "December" numeric
);

CREATE TABLE public.minimum_temperatures_raw
(
    "STATION_NAME" character varying(100),
    "STN_ID" integer,
    "LAT" numeric,
    "LON" numeric,
    "ENSEMBLE" character varying(30),
    "RCP" character varying(30),
    "MODEL" character varying(30),
    "CLIMATOLOGY" character varying(30),
    "Annual" numeric,
    "DJF" numeric,
    "MAM" numeric,
    "JJA" numeric,
    "SON" numeric,
    "NDJFMA" numeric,
    "MJJASO" numeric,
    "January" numeric,
    "February" numeric,
    "March" numeric,
    "April" numeric,
    "May" numeric,
    "June" numeric,
    "July" numeric,
    "August" numeric,
    "September" numeric,
    "October" numeric,
    "November" numeric,
    "December" numeric
);

CREATE TABLE public.nrm_fire_projection_summary_raw
(
    "Site Name" character varying(30),
    "Lat" numeric,
    "Lon" numeric,
    "Model" character varying(30),
    "Experiment" character varying(30),
    "Year" integer,
    "Avg Ann CFFDI" numeric,
    "DPY(12-25) High" numeric,
    "DPY(25-50) Very High" numeric,
    "DPY(50-75) Severe" numeric,
    "DPY(75-100) Extreme" numeric,
    "DPY(over100) Catastrophic" numeric
);

ALTER TABLE public.cl_fire_projection_summary
    ADD FOREIGN KEY (climatology_year)
    REFERENCES public.cl_climatology_years (climatology_year)
    NOT VALID;


ALTER TABLE public.cl_fire_projection_summary
    ADD FOREIGN KEY (model_id)
    REFERENCES public.cl_models (model_id)
    NOT VALID;


ALTER TABLE public.cl_fire_projection_summary
    ADD FOREIGN KEY (rcp_id)
    REFERENCES public.cl_rcp (rcp_id)
    NOT VALID;


ALTER TABLE public.cl_fire_projection_summary
    ADD FOREIGN KEY (station_id)
    REFERENCES public.cl_stations (station_id)
    NOT VALID;


ALTER TABLE public.cl_humidity_09hours
    ADD FOREIGN KEY (climatology_year)
    REFERENCES public.cl_climatology_years (climatology_year)
    NOT VALID;


ALTER TABLE public.cl_humidity_09hours
    ADD FOREIGN KEY (model_id)
    REFERENCES public.cl_models (model_id)
    NOT VALID;


ALTER TABLE public.cl_humidity_09hours
    ADD FOREIGN KEY (rcp_id)
    REFERENCES public.cl_rcp (rcp_id)
    NOT VALID;


ALTER TABLE public.cl_humidity_09hours
    ADD FOREIGN KEY (station_id)
    REFERENCES public.cl_stations (station_id)
    NOT VALID;


ALTER TABLE public.cl_humidity_15hours
    ADD FOREIGN KEY (climatology_year)
    REFERENCES public.cl_climatology_years (climatology_year)
    NOT VALID;


ALTER TABLE public.cl_humidity_15hours
    ADD FOREIGN KEY (model_id)
    REFERENCES public.cl_models (model_id)
    NOT VALID;


ALTER TABLE public.cl_humidity_15hours
    ADD FOREIGN KEY (rcp_id)
    REFERENCES public.cl_rcp (rcp_id)
    NOT VALID;


ALTER TABLE public.cl_humidity_15hours
    ADD FOREIGN KEY (station_id)
    REFERENCES public.cl_stations (station_id)
    NOT VALID;


ALTER TABLE public.cl_maximum_temperatures
    ADD FOREIGN KEY (climatology_year)
    REFERENCES public.cl_climatology_years (climatology_year)
    NOT VALID;


ALTER TABLE public.cl_maximum_temperatures
    ADD FOREIGN KEY (model_id)
    REFERENCES public.cl_models (model_id)
    NOT VALID;


ALTER TABLE public.cl_maximum_temperatures
    ADD FOREIGN KEY (rcp_id)
    REFERENCES public.cl_rcp (rcp_id)
    NOT VALID;


ALTER TABLE public.cl_maximum_temperatures
    ADD FOREIGN KEY (station_id)
    REFERENCES public.cl_stations (station_id)
    NOT VALID;


ALTER TABLE public.cl_mean_temperatures
    ADD FOREIGN KEY (climatology_year)
    REFERENCES public.cl_climatology_years (climatology_year)
    NOT VALID;


ALTER TABLE public.cl_mean_temperatures
    ADD FOREIGN KEY (model_id)
    REFERENCES public.cl_models (model_id)
    NOT VALID;


ALTER TABLE public.cl_mean_temperatures
    ADD FOREIGN KEY (rcp_id)
    REFERENCES public.cl_rcp (rcp_id)
    NOT VALID;


ALTER TABLE public.cl_mean_temperatures
    ADD FOREIGN KEY (station_id)
    REFERENCES public.cl_stations (station_id)
    NOT VALID;


ALTER TABLE public.cl_minimum_temperatures
    ADD FOREIGN KEY (climatology_year)
    REFERENCES public.cl_climatology_years (climatology_year)
    NOT VALID;


ALTER TABLE public.cl_minimum_temperatures
    ADD FOREIGN KEY (model_id)
    REFERENCES public.cl_models (model_id)
    NOT VALID;


ALTER TABLE public.cl_minimum_temperatures
    ADD FOREIGN KEY (rcp_id)
    REFERENCES public.cl_rcp (rcp_id)
    NOT VALID;


ALTER TABLE public.cl_minimum_temperatures
    ADD FOREIGN KEY (station_id)
    REFERENCES public.cl_stations (station_id)
    NOT VALID;

END;